name: Pull Request Workflow

on:
  pull_request:
    types: [opened]  # Runs when a pull request is created

jobs:
  run-on-pull:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Print message
        run: echo "ğŸ” A new Pull Request was opened!"
